name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - CHANGELOG.md
      - poetry.lock
      - pyproject.toml


jobs:
  build:
    name: Continuous Integration
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8","3.9","3.10","3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          poetry install
      - name: Run tests
        run: |
          poetry run pytest -n 3 \
          --cov=extractor --cov-report xml:coverage.xml \
          --cov-config=.code_quality/.coveragerc \
          --disable-warnings
      - name: Get Coverage comments on PR
        if: github.event_name == 'pull_request'
        uses: orgoro/coverage@v3.1
        with:
            coverageFile: coverage.xml
            token: ${{ secrets.GITHUB_TOKEN }}
      - name: Package distribution
        run: poetry build
